name = "lms-senac-tecnico-ia"
main = "worker/src/index.ts"
compatibility_date = "2024-01-01"

# Cloudflare D1 — banco de dados SQLite distribuído
[[d1_databases]]
binding = "DB"
database_name = "lms-progress"
database_id   = "0c14aadc-4dab-4338-a7bd-68a1336f8547"

